# exceptions/first.example.py
gen = (n for n in range (2))
print(next(gen))
print(next(gen))
print(next(gen))
