# context/generator.py
from contextlib import contextmanager

@contextmanager
def my_context_manager():
	print("Entering 'with' context")
	val = object()
	print(id(val))
	try:
		yield val
	except Exception as e:
		print(f"{type(e) = } {e = } {e.__traceback__ = }")
	finally:
		print("Exiting 'with' context")

print("About to enter 'with' context")
with my_context_manager() as val:
	print("Inside 'with' context")
	print(id(val))
	raise Exception("Exception inside 'with' context")
	print("This line will never be reached") # lol, same thing as manager.class.py
print("After 'with' context")
